### ISSUE TITLE
How to compile syntax as a normal tmLanguage (no JSON)?

### ISSUE THREAD

**Issue by jason5122** [pouyakary/vscode-racket#11]
Hi, I'd like to use the syntax as a `.tmLanguage`, XML-based file to be used in Sublime Text (or even better, as a sublime-syntax but that sounds way out of scope here). Can someone please show me how to convert correctly? My converted `.tmLanguage.json` → `.tmLanguage` files are not behaving correctly. Thanks for reading.

**Comment by pouyakary** [comment]
Hey Jason.

I used to work with the `tmLanguage` stuff a long time ago and honestly I have so little memory left. What I do know is that the `.tmLanguage` is basically an Apple Plist XML format. So, I remember that there used to be a tool that converted json to plist and I once used it, it worked fine. The name of the tool is what I have no memory left ☹️. I hope you find it and it works for you.

Good luck.
Pouya

**Comment by jason5122** [comment]
Hi Pouya, no worries! Thanks for the response.
