### ISSUE TITLE
New version inaccessible from marketplace

### ISSUE THREAD

**Issue by Eugleo** [pouyakary/vscode-racket#8]
I'm opening this issue as to easily track the release of the new version on the marketplace. Is there any work to be done before the release happens? I'd be happy to help with it, provided it is any kind of work I am able to help with.

**Comment by pouyakary** [comment]
Sorry I was a little bit busy the past two weeks. There are tiny little things that I have to do but I promise you that you’ll get the new version in the market by end of this week. How’s that?

**Comment by Eugleo** [comment]
Oh, don't rush it! :-) I just didn't want to check the marketplace every two days to see if it's there, so I setup this issue, which will "remind" me itself when it gets closed.

**Comment by bthesorceror** [comment]
the newest version I see on the marketplace is 0.0.3, is that the newest version?

**Comment by pouyakary** [comment]
@bthesorceror 

There is a newer version that we're working on. The syntax rules are changed but they still need changes to be usable, so it'll take a while but a newer version will be released soon.
